MAJORITY_RELIGIOUS_POPULATION_DB = 'data/world-religions/national_majority_data_by_year.csv'
MAJ_INT_RELIGIOUS_POPULATION = 'data/world-religions/national_interpolated_data.csv'
TERRORISM_DB = 'data/terrorism_database/terrorism_db.csv'
PF_RELIGIOUS_FREEDOM = 'data/human-freedom-index/religion_pf_freedom.csv'
HAPPINESS_DB = 'data/world-happiness-report/2015_raw.csv'
